# Javascript Node CircleCI 2.0 configuration file
#
# Check {{ '/2.0/language-javascript/' | docs_url }} for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:14.8.0

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install --frozen-lockfile
      - run:
          name: Run tests
          command: yarn lerna run tests

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .
  version:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - add_ssh_keys:
          fingerprints:
            - "c2:fd:ff:c2:78:47:51:f9:09:d3:87:50:70:13:8b:51"
      - run:
          name: hack
          command: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - run:
          command: |
            git config --global user.name "Circle CI"
            git config --global user.email "circleci-bot@example.com"
      - run:
          name: checkout main
          command: git checkout main
      - run:
          name: bump version
          command: yarn lerna version prerelease --preid beta --yes
      - run:
          name: push back to develop
          command: |
            git checkout develop
            git merge --no-ff -m "version bump [ci skip]" "$CIRCLE_BRANCH"
            git push origin develop
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: yarn lerna publish from-git --yes

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: [/^develop$/, /^release.*/]
      - version:
          requires:
            - test
          filters:
            branches:
              only: /^release.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^@sammiio.*/
            branches:
              only: main
